### ISSUE TITLE
v0.3 Roadmap

### ISSUE THREAD

**Issue by rndxelement** [rndxelement/pyytsync#1]
- [x] backend: Move javascript code into [a] .js file[s]
- [ ] backend: Fix video pane not scaling correctly (in some cases there is empty space at the bottom)
- [ ] backend: Review synchronization code, improve synchronization
- [ ] frontend: Visually differentiate between header and playlist
- [ ] frontend: Light mode
- [ ] frontend: Switch between light and dark mode
